sports_category = [
    {
        "question": "Which of these is NOT a shot in badminton?",
        "options": ["smash", "Drop", "Dunk", "Drive"],
        "answer": "Dunk",
        "category": "Sports",
    },
    {
        "question": "Which organization governs international badminton?",
        "options": ["ITF", "FIFA", "BWF", "ICC"],
        "answer": "BWF",
        "category": "Sports",
    },
    {
        "question": "Which of these is NOT a part of a badminton racket?",
        "options": ["Shaft", "Head", "Stringbed", "Handlebar"],
        "answer": "Handlebar",
        "category": "Sports",
    },
    {
        "question": " Which country has won the most Thomas Cup titles in badminton?",
        "options": ["China", "India", "Indonesia", "Malaysia"],
        "answer": "Indonesia",
        "category": "Sports",
    },
    {
        "question": "In badminton, what does the term 'love' mean?",
        "options": [
            "15 points",
            "A score of Zero",
            "Winning by two points",
            "A high score",
        ],
        "answer": "A score of zero",
        "category": "Sports",
    },
    {
        "question": " Which of these is NOT a type of badminton serve?",
        "options": ["Flick serve", "Underarm serve", "Backhand serve", "Topspin serve"],
        "answer": "Topspin serve",
        "category": "Sports",
    },
    {
        "question": " In which year were the first modern Olympic Games held?",
        "options": ["1986", "1900", "1896", "1912"],
        "answer": "1896",
        "category": "Sports",
    },
    {
        "question": "Which country has won the most Olympic medals in history?",
        "options": ["China", "Australia", "USA", "Russia"],
        "answer": "USA",
        "category": "Sports",
    },
    {
        "question": "What is the official motto of the Olympic Games?",
        "options": ["Faster,Higher,stronger-Together", "sportsmanship and strength"],
        "answer": "Faster,Higher,stronger-Together",
        "category": "Sports",
    },
    {
        "question": "Which city was the first to host the Summer Olympics three times?",
        "options": ["Paris", "Los Angeles", "London", "Athens"],
        "answer": "London",
        "category": "Sports",
    },
    {
        "question": "In which sport did India win its first Olympic gold medal?",
        "options": ["Hockey", "Wrestling", "Shooting", "Badminton"],
        "answer": "Hockey",
        "category": "Sports",
    },
    {
        "question": "Which country is considered the birthplace of kabaddi?",
        "options": ["Iran", "India", "Pakistan", "Nepal"],
        "answer": "India",
        "category": "Sports",
    },
    {
        "question": "What term describes the act of chanting 'kabaddi' while raiding?",
        "options": ["Kabaddi mantra", "Cant", "chanting round", "Kabaddi call"],
        "answer": "cant",
        "category": "Sports",
    },
    {
        "question": "In Pro Kabaddi League, what is the maximum number of foreign players allowed in a team?",
        "options": ["2", "3", "4", "5"],
        "answer": "4",
        "category": "Sports",
    },
    {
        "question": "Which team won the first season of the Pro Kabaddi League in 2014?",
        "options": [
            "U Mumba",
            "Jaipur Pink Panthers",
            "Bengaluru Bulls",
            "Patna Pirates",
        ],
        "answer": "Jaipur Pink Panthers",
        "category": "Sports",
    },
    {
        "question": "Which Indian state is known for popularizing kabaddi as a traditional sport?",
        "options": ["Odisha", "Tamil Nadu", "Haryana", "Punnjab"],
        "answer": "Haryana",
        "category": "Sports",
    },
    {
        "question": "Which player holds the record for the most goals scored in a single World Cup tournament?",
        "options": ["Pele", "MBappe", "Just Fontaine", "Ronaldo"],
        "answer": "Just Fontaine",
        "category": "Sports",
    },
    {
        "question": "Which team has won the most UEFA Champions League titles?",
        "options": ["Barcelona", "Bayern Munich", "Real Madrid", "AC Milan"],
        "answer": "Real Madrid",
        "category": "Sports",
    },
    {
        "question": "Who was awarded the Ballon d'Or the most times by 2023?",
        "options": [
            "Cristiano Ronaldo",
            "Johan Cruyff",
            "Lionel Messi",
            "Michel Platini",
        ],
        "answer": "Lionel Messi",
        "category": "Sports",
    },
    {
        "question": "What does FIFA stand for?",
        "options": [
            " Federation of International Football Associations",
            "Football International Federation Association",
            "Fédération Internationale de Football Association",
            "Football Institute of the Federation Association",
        ],
        "answer": "Fédération Internationale de Football Association",
        "category": "Sports",
    },
    {
        "question": "Which country has won the most FIFA World Cup titles?",
        "options": ["Germany", "Italy", "Argentina", "Brazil"],
        "answer": "Brazil",
        "category": "Sports",
    },
    {
        "question": "Which English club won the 'Treble' (Premier League, FA Cup, and Champions League) in 1999?",
        "options": ["Liverpool", "Manchester United", "Arsenal", "Chelsea"],
        "answer": "Manchester United",
        "category": "Sports",
    },
    {
        "question": "In which year RCB won the IPL trophy",
        "options": ["2016", "2020", "Never Won", "2010"],
        "answer": "Never Won",
        "category": "Sports",
    },
    {
        "question": "In Test cricket, who holds the record for the highest individual score as a wicketkeeper?",
        "options": ["Kumar Sangakkara", "Adam Gilchrist", "MS Dhoni", "Andy Flower"],
        "answer": "Andy Flower",
        "category": "Sports",
    },
    {
        "question": "Which bowler has taken the most wickets in a single edition of the ICC Cricket World Cup?",
        "options": [
            "Glenn McGrath",
            "Mitchell Starc",
            "Muttiah Muralitharan",
            "Lasith Malinga",
        ],
        "answer": "Mitchell Starc",
        "category": "Sports",
    },
    {
        "question": "Who was the first cricketer to take 10 wickets in a single Test innings?",
        "options": ["Jim Laker", "Anil Kumble", "Shane Warne", "Richard Hadlee"],
        "answer": "Jim Laker",
        "category": "Sports",
    },
    {
        "question": "Who was the first bowler to reach 500 wickets in Test cricket?",
        "options": ["Richard Hadlee", "Kapil Dev", "Courtney Walsh", "Wasim Akram"],
        "answer": "Richard Hadlee",
        "category": "Sports",
    },
    {
        "question": "Which cricketer has scored the most runs in T20 Internationals?",
        "options": ["Virat Kohli", "Ab De villiers", "Chris Gayle", "Rohit Sharma"],
        "answer": "Rohit Sharma",
        "category": "Sports",
    },
    {
        "question": "Who is the only player to have taken two hat-tricks in the same World Cup?",
        "options": ["Lasith Malinga", "Trent Boult", "Brett Lee", "Imran Tahir"],
        "answer": "Lasith Malinga",
        "category": "Sports",
    },
    {
        "question": "Who won the most number of orange cap in IPL history ",
        "options": ["Virat Kohli", "David Warner", "KL Rahul", "Brendon Mccullum"],
        "answer": "David Warner",
        "category": "Sports",
    },
]

indian_gk = [
    {
        "question": "Who was the first President of India?",
        "options": [
            "Dr. Rajendra Prasad",
            "Dr. Sarvepalli Radhakrishnan",
            "Jawaharlal Nehru",
            "Mahatma Gandhi",
        ],
        "answer": "Dr. Rajendra Prasad",
        "category": "Indian GK",
    },
    {
        "question": "Who was the first Prime Minister of India?",
        "options": [
            "Jawaharlal Nehru",
            "Dr. Rajendra Prasad",
            "Mahatma Gandhi",
            "Indira Gandhi",
        ],
        "answer": "Jawaharlal Nehru",
        "category": "Indian GK",
    },
    {
        "question": "What is the capital of India?",
        "options": ["New Delhi", "Mumbai", "Chennai", "Kolkata"],
        "answer": "New Delhi",
        "category": "Indian GK",
    },
    {
        "question": "Which river is the longest in India?",
        "options": ["Ganges", "Yamuna", "Brahmaputra", "Indus"],
        "answer": "Ganges",
        "category": "Indian GK",
    },
    {
        "question": "Who was the first Indian to go to space?",
        "options": [
            "Rakesh Sharma",
            "Kalpana Chawla",
            "A.P.J. Abdul Kalam",
            "Rajiv Gandhi",
        ],
        "answer": "Rakesh Sharma",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the largest state in India by population?",
        "options": ["Uttar Pradesh", "Maharashtra", "Bihar", "West Bengal"],
        "answer": "Uttar Pradesh",
        "category": "Indian GK",
    },
    {
        "question": "Who is the author of the book 'The Discovery of India'?",
        "options": [
            "Jawaharlal Nehru",
            "Mahatma Gandhi",
            "Rabindranath Tagore",
            "Subhas Chandra Bose",
        ],
        "answer": "Jawaharlal Nehru",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the largest city in India by population?",
        "options": ["Delhi", "Mumbai", "Kolkata", "Chennai"],
        "answer": "Delhi",
        "category": "Indian GK",
    },
    {
        "question": "Who was the first Indian to win the Nobel Prize?",
        "options": [
            "Rabindranath Tagore",
            "C. V. Raman",
            "Amartya Sen",
            "Hargobind Khorana",
        ],
        "answer": "Rabindranath Tagore",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the largest river in India by discharge?",
        "options": ["Brahmaputra", "Ganges", "Yamuna", "Indus"],
        "answer": "Brahmaputra",
        "category": "Indian GK",
    },
    {
        "question": "Who is the author of the book 'My experiments with Truth'?",
        "options": [
            "Mahatma Gandhi",
            "Jawaharlal Nehru",
            "Rabindranath Tagore",
            "Subhas Chandra Bose",
        ],
        "answer": "Mahatma Gandhi",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the highest mountain peak in India?",
        "options": ["Mount Everest", "Nanda Devi", "Kangchenjunga", "Annapurna"],
        "answer": "Kangchenjunga",
        "category": "Indian GK",
    },
    {
        "question": "Who is the current Chief Justice of India?",
        "options": [
            "N. V. Ramana",
            "U. U. Lalit",
            "D. Y. Chandrachud",
            "A. M. Khanwilkar",
        ],
        "answer": "D. Y. Chandrachud",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the largest state in India by area?",
        "options": ["Rajasthan", "Madhya Pradesh", "Maharashtra", "Uttar Pradesh"],
        "answer": "Rajasthan",
        "category": "Indian GK",
    },
    {
        "question": "Who was the first Indian woman to go to space?",
        "options": ["Kalpana Chawla", "Sunita Williams", "P. V. Sindhu", "Mira Nair"],
        "answer": "Kalpana Chawla",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the smallest state in India by population?",
        "options": ["Sikkim", "Mizoram", "Arunachal Pradesh", "Nagaland"],
        "answer": "Sikkim",
        "category": "Indian GK",
    },
    {
        "question": "Who is the author of the book 'The Argumentative Indian'?",
        "options": [
            "Amartya Sen",
            "Rabindranath Tagore",
            "Jawaharlal Nehru",
            "Subhas Chandra Bose",
        ],
        "answer": "Amartya Sen",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the largest city in India by land area?",
        "options": ["Delhi", "Mumbai", "Kolkata", "Chennai"],
        "answer": "Delhi",
        "category": "Indian GK",
    },
    {
        "question": "Who was the first Indian to win the Booker Prize?",
        "options": ["Arundhati Roy", "Salman Rushdie", "Vikram Seth", "Amitav Ghosh"],
        "answer": "Arundhati Roy",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the largest state in India by coastline?",
        "options": ["Gujarat", "Maharashtra", "Kerala", "Tamil Nadu"],
        "answer": "Gujarat",
        "category": "Indian GK",
    },
    {
        "question": "Who is the author of the book 'The God of Small Things'?",
        "options": ["Arundhati Roy", "Salman Rushdie", "Vikram Seth", "Amitav Ghosh"],
        "answer": "Arundhati Roy",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the highest waterfall in India?",
        "options": [
            "Jog Falls",
            "Kunchikal Falls",
            "Sivasamudram Falls",
            "Hogenakkal Falls",
        ],
        "answer": "Jog Falls",
        "category": "Indian GK",
    },
    {
        "question": "Who is the author of the book 'The Namesake'?",
        "options": ["Jhumpa Lahiri", "Salman Rushdie", "Vikram Seth", "Amitav Ghosh"],
        "answer": "Jhumpa Lahiri",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the largest city in India by population density?",
        "options": ["Delhi", "Mumbai", "Kolkata", "Chennai"],
        "answer": "Delhi",
        "category": "Indian GK",
    },
    {
        "question": "Who was the first Indian to win the Academy Award?",
        "options": ["Bhanu Athaiya", "Resul Pookutty", "Rahman", "S. S. Rajamouli"],
        "answer": "Bhanu Athaiya",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the largest state in India by GDP?",
        "options": ["Maharashtra", "Uttar Pradesh", "Tamil Nadu", "Gujarat"],
        "answer": "Maharashtra",
        "category": "Indian GK",
    },
    {
        "question": "Who is the author of the book 'The Inheritance of Loss'?",
        "options": ["Kiran Desai", "Salman Rushdie", "Vikram Seth", "Amitav Ghosh"],
        "answer": "Kiran Desai",
        "category": "Indian GK",
    },
    {
        "question": "What is the name of the highest mountain peak in the Western Ghats?",
        "options": ["Anamudi", "Meeshapulimala", "Doddabetta", "Kalsubai"],
        "answer": "Anamudi",
        "category": "Indian GK",
    },
    {
        "question": "Who is the author of the book 'The White Tiger'?",
        "options": ["Aravind Adiga", "Salman Rushdie", "Vikram Seth", "Amitav Ghosh"],
        "answer": "Aravind Adiga",
        "category": "Indian GK",
    },
    {
        "question": "Which of the following is the national song of India?",
        "options": [
            "Jana Gana Mana",
            "Vande Mataram",
            "Aye Mere Watan Ke Logo",
            "Sare Jahan Se Achchha",
        ],
        "answer": "Vande Mataram",
        "category": "Indian GK",
    },
]

programming_questions = [
    {
        "question": "What is the output of the expression '2' + 2 in JavaScript?",
        "options": ["22", "4", "NaN", "undefined"],
        "answer": "22",
        "category": "Programming",
    },
    {
        "question": "Which language is known as the 'mother of all programming languages'?",
        "options": ["C", "Assembly", "COBOL", "Fortran"],
        "answer": "Fortran",
        "category": "Programming",
    },
    {
        "question": "Which of the following is not a Python data type?",
        "options": ["list", "set", "tuple", "map"],
        "answer": "map",
        "category": "Programming",
    },
    {
        "question": "In which year was the Python programming language released?",
        "options": ["1991", "1989", "1995", "2000"],
        "answer": "1991",
        "category": "Programming",
    },
    {
        "question": "Who is the creator of the Linux kernel?",
        "options": [
            "Linus Torvalds",
            "Richard Stallman",
            "Dennis Ritchie",
            "Ken Thompson",
        ],
        "answer": "Linus Torvalds",
        "category": "Programming",
    },
    {
        "question": "Which company developed the Java programming language?",
        "options": ["Microsoft", "Sun Microsystems", "Google", "Apple"],
        "answer": "Sun Microsystems",
        "category": "Programming",
    },
    {
        "question": "What does 'HTML' stand for?",
        "options": [
            "HyperText Markup Language",
            "Hyperlinks and Text Markup Language",
            "HighText Machine Language",
            "Hyperlinking Text Marking Language",
        ],
        "answer": "HyperText Markup Language",
        "category": "Programming",
    },
    {
        "question": "Which of the following is a JavaScript framework?",
        "options": ["Django", "Flask", "React", "Laravel"],
        "answer": "React",
        "category": "Programming",
    },
    {
        "question": "What is the main purpose of CSS in web development?",
        "options": [
            "To structure the web page",
            "To style the web page",
            "To program the web page",
            "To store data",
        ],
        "answer": "To style the web page",
        "category": "Programming",
    },
    {
        "question": "Which language is used for styling web pages?",
        "options": ["HTML", "JQuery", "CSS", "XML"],
        "answer": "CSS",
        "category": "Programming",
    },
    {
        "question": "Who is known as the father of the World Wide Web?",
        "options": ["Tim Berners-Lee", "Vint Cerf", "Linus Torvalds", "Bill Gates"],
        "answer": "Tim Berners-Lee",
        "category": "Programming",
    },
    {
        "question": "Which of the following is a server-side scripting language?",
        "options": ["JavaScript", "PHP", "CSS", "HTML"],
        "answer": "PHP",
        "category": "Programming",
    },
    {
        "question": "Which of the following is not a programming language?",
        "options": ["Python", "Java", "HTML", "C++"],
        "answer": "HTML",
        "category": "Programming",
    },
    {
        "question": "What is the file extension of Python files?",
        "options": [".py", ".java", ".php", ".html"],
        "answer": ".py",
        "category": "Programming",
    },
    {
        "question": "In which of the following languages is indentation significant?",
        "options": ["C", "Java", "Python", "C++"],
        "answer": "Python",
        "category": "Programming",
    },
    {
        "question": "Which of the following is a NoSQL database?",
        "options": ["MySQL", "PostgreSQL", "MongoDB", "Oracle"],
        "answer": "MongoDB",
        "category": "Programming",
    },
    {
        "question": "Which protocol is used for sending emails?",
        "options": ["HTTP", "WS", "SMTP", "FTP"],
        "answer": "SMTP",
        "category": "Programming",
    },
    {
        "question": "What is the default port for HTTP?",
        "options": ["80", "443", "21", "25"],
        "answer": "80",
        "category": "Programming",
    },
    {
        "question": "Which data structure uses LIFO order?",
        "options": ["Queue", "Stack", "Array", "Linked List"],
        "answer": "Stack",
        "category": "Programming",
    },
    {
        "question": "Which keyword is used to declare a variable in JavaScript?",
        "options": ["var", "let", "const", "All of the above"],
        "answer": "All of the above",
        "category": "Programming",
    },
    {
        "question": "What is the time complexity of binary search?",
        "options": ["O(n)", "O(log n)", "O(n^2)", "O(1)"],
        "answer": "O(log n)",
        "category": "Programming",
    },
    {
        "question": "Which of the following is a strongly typed language?",
        "options": ["Python", "JavaScript", "Java", "PHP"],
        "answer": "Java",
        "category": "Programming",
    },
    {
        "question": "Which of the following is a front-end framework?",
        "options": ["Django", "Flask", "Angular", "Node.js"],
        "answer": "Angular",
        "category": "Programming",
    },
    {
        "question": "What is the main feature of a functional programming language?",
        "options": ["Objects", "Functions", "Classes", "Inheritance"],
        "answer": "Functions",
        "category": "Programming",
    },
    {
        "question": "Which language is primarily used for data science?",
        "options": ["C", "Java", "Python", "PHP"],
        "answer": "Python",
        "category": "Programming",
    },
    {
        "question": "What does 'SQL' stand for?",
        "options": [
            "Structured Query Language",
            "Sequential Query Language",
            "Structured Question Language",
            "Sequential Question Language",
        ],
        "answer": "Structured Query Language",
        "category": "Programming",
    },
    {
        "question": "Which of the following is a built-in Python function?",
        "options": ["print()", "document()", "echo()", "System.out.println()"],
        "answer": "print()",
        "category": "Programming",
    },
    {
        "question": "Which keyword is used to define a function in Python?",
        "options": ["def", "function", "void", "func"],
        "answer": "def",
        "category": "Programming",
    },
    {
        "question": "Which of the following is a version control system?",
        "options": ["Git", "Docker", "Kubernetes", "AWS"],
        "answer": "Git",
        "category": "Programming",
    },
    {
        "question": "Which of the following is used to make a web page interactive?",
        "options": ["CSS", "HTML", "JavaScript", "SQL"],
        "answer": "JavaScript",
        "category": "Programming",
    },
]
